name: CI for Django Monorepo

on:
  pull_request:
    paths:
      - 'project1/**'
      - 'project2/**'
      - 'shared/**'

jobs:
  check-project1:
    if: github.event.pull_request.head.repo.full_name == 'owner/repo' && (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'project1/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd project1
          poetry install
      - name: Run tests
        run: |
          cd project1
          poetry run pytest

  check-project2:
    if: github.event.pull_request.head.repo.full_name == 'owner/repo' && (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'project2/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd project2
          poetry install
      - name: Run tests
        run: |
          cd project2
          poetry run pytest

  check-shared:
    if: github.event.pull_request.head.repo.full_name == 'owner/repo' && (github.event_name == 'pull_request' && contains(github.event.pull_request.changed_files, 'shared/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies for project1
        run: |
          cd project1
          poetry install
      - name: Run tests for project1
        run: |
          cd project1
          poetry run pytest
      - name: Install dependencies for project2
        run: |
          cd project2
          poetry install
      - name: Run tests for project2
        run: |
          cd project2
          poetry run pytest

